# Generated by Django 6.0.2 on 2026-07-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_savedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedvideo',
            name='video_format',
            field=models.CharField(choices=[('short', '短影片'), ('long', '長影片')], default='long', max_length=10),
        ),
    ]
